### ISSUE TITLE
MDDL dataset download link not working 

### ISSUE THREAD

**Issue by fvahdati** [sunlightsgy/MDDL#2]
Hi I tried so many times to download your dataset but this link showing 404 
https://mailstsinghuaeducn-my.sharepoint.com/:u:/g/personal/sgy16_mails_tsinghua_edu_cn/EbcI8AuOdCVJp7Itjzx3U_4BkJf1iDJiGykLwkgNHDKHyg?e=lnuY91

**Comment by asma1598** [comment]
I can't download the dataset also.

**Comment by sunlightsgy** [comment]
It looks like the link of onedrive has been expired. I will try to find the original dataset and push it to another place later.

**Comment by sunlightsgy** [comment]
Updated
